apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: rojascjp/sopesproyect2:backend
        imagePullPolicy: Always
        name: backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: project
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 10000
  selector:
    app: backend