apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-client
  name: grpc-client
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - image: rojascjp/sopesproyect2:client
        imagePullPolicy: Always
        name: grpc-client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client
  name: grpc-client
  namespace: project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 4300
  selector:
    app: grpc-client
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-client-ingress
  namespace: project
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  ingressClassName: nginx
  rules:
<<<<<<< HEAD:Kubernetes/green.yaml
    - host: green.so1p2g1.tk
=======
    - host: blue.so1p2g1.tk
>>>>>>> 733f63cd679dcce149a86c382907911ad05a228f:Kubernetes/pruebas/grpc-client.yaml
      http:
        paths:
          - backend:
              service:
                name: grpc-client
                port: 
                  number: 8080
            path: /
            pathType: Prefix
