apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-pub
  name: redis-pub
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pub
  template:
    metadata:
      labels:
        app: redis-pub
    spec:
      containers:
      - image: rojascjp/sopesproyect2:redis-pub
        imagePullPolicy: Always
        name: redis-pub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-pub
  name: redis-pub
  namespace: project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: redis-pub
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-pub-ingress
  namespace: project
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  ingressClassName: nginx
  rules:
    - host: green.so1p2g1.tk
      http:
        paths:
          - backend:
              service:
                name: redis-pub
                port: 
                  number: 8080
            path: /
            pathType: Prefix